# cspell:ignore esbuild, unrs, jotai, nuqs, xyflow

packages:
  - apps/*
  - packages/*
  - tooling/*

allowUnusedPatches: false

catalog:
  "@stylexjs/babel-plugin": ^0.15.2
  "@stylexjs/postcss-plugin": ^0.15.2
  "@stylexjs/stylex": ^0.15.2
  "@types/node": ^24.2.1
  "@types/react": ^19.1.9
  "@types/react-dom": ^19.1.7
  "@vitejs/plugin-react": ^5.0.0
  babel-plugin-react-compiler: 19.1.0-rc.2
  eslint: ^9.33.0
  react: 0.0.0-experimental-be11cb5c-20250804
  react-dom: 0.0.0-experimental-be11cb5c-20250804
  typescript: ^5.9.2
  vite: ^7.1.1

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - unrs-resolver

overrides:
  eslint-import-resolver-typescript>eslint-plugin-import: "-"
  vite: npm:rolldown-vite@latest

engineStrict: true
packageManagerStrictVersion: true
saveWorkspaceProtocol: true
linkWorkspacePackages: true
managePackageManagerVersions: false
verifyDepsBeforeRun: "error"
strictDepBuilds: true
