# cspell:ignore esbuild, msgpackr, unrs, protobufjs

packages:
  - apps/*
  - packages/*
  - tooling/*

allowUnusedPatches: false

catalog:
  "@effect/ai": ^0.26.0
  "@effect/ai-anthropic": ^0.16.0
  "@effect/ai-google": ^0.5.0
  "@effect/cluster": ^0.48.0
  "@effect/experimental": ^0.54.6
  "@effect/opentelemetry": ^0.56.2
  "@effect/platform": ^0.90.3
  "@effect/platform-node": ^0.96.0
  "@effect/rpc": ^0.69.0
  "@effect/sql": ^0.44.1
  "@effect/sql-pg": ^0.45.0
  "@effect/workflow": ^0.9.0
  "@opentelemetry/sdk-trace-web": ^2.0.1
  "@stylexjs/babel-plugin": ^0.15.3
  "@stylexjs/postcss-plugin": ^0.15.3
  "@stylexjs/stylex": ^0.15.3
  "@types/node": ^24.3.0
  "@types/react": ^19.1.10
  "@types/react-dom": ^19.1.7
  "@vitejs/plugin-react": ^5.0.0
  babel-plugin-react-compiler: 19.1.0-rc.2
  effect: ^3.17.7
  eslint: ^9.33.0
  react: 0.0.0-experimental-f1222f76-20250812
  react-dom: 0.0.0-experimental-f1222f76-20250812
  tsx: ^4.20.4
  typescript: ^5.9.2
  vite: ^7.1.2
  wait-on: ^8.0.4

engineStrict: true

linkWorkspacePackages: true

managePackageManagerVersions: false

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - msgpackr-extract
  - protobufjs
  - unrs-resolver

overrides:
  eslint-import-resolver-typescript>eslint-plugin-import: "-"
  react: "catalog:"
  react-dom: "catalog:"

packageManagerStrictVersion: true

patchedDependencies:
  "@tanstack/db": patches/@tanstack__db.patch
  "@tanstack/electric-db-collection": patches/@tanstack__electric-db-collection.patch
  prettier-plugin-sql@0.19.2: patches/prettier-plugin-sql.patch

saveWorkspaceProtocol: true

strictDepBuilds: true

verifyDepsBeforeRun: error
