{
 "title": "Bella",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Response plan generation duration",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum(rate(traces_spanmetrics_latency_bucket{span_name=\"Bella/Core/getResponsePlan\"}[5m])) by (le)\n)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum(rate(traces_spanmetrics_latency_bucket{span_name=\"Bella/Core/getResponsePlan\"}[5m])) by (le)\n)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum(rate(traces_spanmetrics_latency_bucket{span_name=\"Bella/Core/getResponsePlan\"}[5m])) by (le)\n)",
     "legendFormat": "P99"
    },
    {
     "expr": "sum(rate(traces_spanmetrics_latency_sum{span_name=\"Bella/Core/getResponsePlan\"}[5m]))\n/\nsum(rate(traces_spanmetrics_latency_count{span_name=\"Bella/Core/getResponsePlan\"}[5m]))\n",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Message generation workflow full duration",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(traces_spanmetrics_latency_bucket{span_name=~\"Workflow/GenerateMessage\\\\([^)]+\\\\)\\\\.run\"\n}[5m])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(traces_spanmetrics_latency_bucket{span_name=~\"Workflow/GenerateMessage\\\\([^)]+\\\\)\\\\.run\"\n}[5m])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(traces_spanmetrics_latency_bucket{span_name=~\"Workflow/GenerateMessage\\\\([^)]+\\\\)\\\\.run\"\n}[5m])))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Model usage",
   "type": "piechart",
   "description": "Count of each model usage for fulfilled responses",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(model) (\n  increase(model_usage_total[$__range])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Responses",
   "type": "piechart",
   "description": "Count of each response type",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(type) (\n  increase(response_total[$__range])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}